### ISSUE TITLE
Create scoring system

### ISSUE THREAD

**Issue by hhoopes** [brennanholtzclaw/game_time#40]
Score each hole and display on screen in a little golf card

**Comment by hhoopes** [comment]
Need to check with Brenna via Romeeka if we need to move away from session scoring

**Comment by brennanholtzclaw** [comment]
Also, some terminology:

If your strokes are LESS than par (ie; par 4, and you have 2 strokes), you're two strokes UNDER Par. Vice-Versa for being over.

Your score for a single hole is expressed as it's relationship to par (so in the above scenario your score would be -2). 

Your score for the course is expressed as your total number of strokes on all holes vs. the sum of all of the pars( so on our course of Par 2, 3, 4  - the overall par is 7).
